### PR TITLE
Add Tristan

### PR DESCRIPTION
**Pull request by trdyer**
@npars because @daynemay made me

### CODE REVIEW

**Comment by daynemay** [comment]
@Lykathia, FYI

**Comment by dpatterson-aio** [comment]
I'm assuming this is for when you "Request Changes"

**Comment by Lykathia** [comment]
Not using git LFS.

Shame

**Comment by trdyer** [comment]
@dpatterson-aio yeah, we use some of these gems fairly frequently...

**Comment by npars** [comment]
Not really a plus one but I'll accept it

**Pull request merged**
