### PR TITLE
+4 gifs

### PR DESCRIPTION
**Pull request by dpatterson-aio**
this is the most "contributing" i've done for the open source community so far to date

### CODE REVIEW

**Comment by npars** [comment]
Please put the original gifs in `_orig` and run `cd _orig; for f in *.gif; do gifsicle --resize-width 300 -O3 -i "$f" -o ../gifs/"$f"; done`

**Comment by npars** [comment]
Also, feel free to submit your older ones

**Comment by dpatterson-aio** [comment]
ah, half of them are resized...i'll fix this up later!

**Comment by npars** [comment]
Could you remove the rewrites form the commit and squash it? Pretty sure every time the image changes it will add size to the repo

**Comment by dpatterson-aio** [comment]
yeah, ignore this PR until further notice! it's super messed up at the moment

**Pull request closed without merging**
